label: 'Головна сторінка'
tags:
  keywords: 'conference, конференція, Drupal, Drupal conference, Kyiv Drupal, Kyiv Drupal Camp, конференція про Друпал, Drupal community'
  description: 'DrupalCamp Kyiv 2018 - головна щорічна подія Drupal-спільноти відбудеться 23-24 червня 2018, в Києві, в iZone Creative Community'
