description: 'Пошук файлів та керування ними.'
display:
  default:
    display_title: Головне
    display_options:
      exposed_form:
        options:
          submit_button: Фільтр
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
      pager:
        options:
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      fields:
        fid:
          label: Fid
        filename:
          label: 'Назва (ім''я)'
        type:
          label: Тип
        filesize:
          label: Розмір
        status:
          label: Стан
        changed:
          label: Змінено
          separator: ', '
        created:
          label: Створено
          separator: ', '
        count:
          label: 'Використано в'
          format_plural_string: !!binary QGNvdW50INC80ZbRgdGG0LUDQGNvdW50INC80ZbRgdGG0Y8DQGNvdW50INC80ZbRgdGG0Yw=
        operations:
          label: Операції
      filters:
        filename:
          expose:
            label: 'Назва файла'
        status:
          expose:
            label: Стан
        type:
          expose:
            label: Тип
      title: Файли
      empty:
        area_text_custom:
          content: 'Файли відсутні.'
  overview:
    display_title: 'Огляд файлів'
    display_options:
      menu:
        title: Файли
  usage:
    display_title: 'Використання файла'
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      fields:
        entity_label:
          label: Сутність
        type:
          label: 'Тип сутності'
        module:
          label: 'Реєстрація модуля'
        count:
          label: 'Підрахунок використань'
          format_plural_string: !!binary QGNvdW50INC80ZbRgdGG0LUDQGNvdW50INC80ZbRgdGG0Y8DQGNvdW50INC80ZbRgdGG0Yw=
      title: 'Використання файла'
      arguments:
        fid:
          exception:
            title: Все
          title: 'Відомості про використання файла для {{ arguments.fid }}'
      menu:
        title: Використання
