display:
  default:
    display_options:
      filters:
        status:
          group_info:
            group_items:
              1:
                value: '1'
                title: Opublikowane
              2:
                title: Nieopublikowany
            label: 'Status opublikowania'
        title:
          expose:
            label: Tytuł
        type:
          expose:
            label: 'Rodzaj zawartości'
        langcode:
          expose:
            label: Język
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      fields:
        title:
          label: Tytuł
        type:
          label: 'Rodzaj zawartości'
        name:
          label: Autor
        status:
          settings:
            format_custom_true: Opublikowane
            format_custom_false: Nieopublikowany
        changed:
          label: Uaktualniono
        operations:
          label: Operacje
      title: Zawartość
      empty:
        area_text_custom:
          content: 'Brak zawartości.'
    display_title: Główny
  page_1:
    display_options:
      menu:
        title: Zawartość
      tab_options:
        title: Zawartość
        description: 'Znajdź i zarządzaj treścią'
    display_title: Strona
label: Zawartość
description: 'Wyszukiwanie i zarządzanie zawartością.'
