display:
  default:
    display_title: Główny
    display_options:
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      pager:
        options:
          expose:
            items_per_page_label: 'Elementów na stronę'
            items_per_page_options_all_label: '- Wszystko -'
            offset_label: Przesunięcie
      fields:
        filename:
          label: Nazwa
        type:
          label: Typ
        filesize:
          label: Rozmiar
        status:
          label: Status
        changed:
          label: Zmieniono
        created:
          label: Utworzono
        count:
          label: 'Użyte w'
        operations:
          label: Operacje
      filters:
        filename:
          expose:
            label: 'Nazwa pliku'
        status:
          expose:
            label: Status
        type:
          expose:
            label: Typ
      title: Pliki
  overview:
    display_options:
      menu:
        title: Pliki
  usage:
    display_title: 'Wykorzystanie plików'
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Elementów na stronę'
            items_per_page_options_all_label: '- Wszystko -'
            offset_label: Przesunięcie
      fields:
        entity_label:
          label: Encja
        type:
          label: 'Typ encji'
        count:
          label: 'Ilość wystąpień'
      title: 'Wykorzystanie plików'
      arguments:
        fid:
          exception:
            title: Wszystko
      menu:
        title: Użycie
