elements: "name:\n  '#placeholder': Name\nsubject:\n  '#placeholder': Topic\ntelephone:\n  '#placeholder': Phone\nmessage:\n  '#placeholder': 'Few words about yourself'\n"
handlers:
  email_notification:
    settings:
      body: "Name: [webform_submission:values:name:value]<br />\r\nMail: [webform_submission:values:email:raw]<br />\r\nTheme: [webform_submission:values:subject:value]<br />\r\nTelephone: [webform_submission:values:telephone:value]<br />\r\nAbout me: [webform_submission:values:message:value]"
settings:
  confirmation_message: 'Thank you!<br /> Your message has been sent.<br /> Organizing Committee will receive your request and contact you soon.'
