default_button: true
default_message: true
default_tab: true
default_tab_edit: true
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  article: true
  page: true
  news: true
  sponsors: true
  speaker: true
  presentation: true
message:
  article: true
  page: true
  news: true
  sponsors: true
  speaker: true
  presentation: true
tab:
  article: true
  page: true
  news: true
  sponsors: true
  speaker: true
  presentation: true
tab_edit:
  article: true
  page: true
  news: true
  sponsors: true
  speaker: true
  presentation: true
