smtp_on: true
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: org.drupalcamp.kyiv@gmail.com
smtp_password: 'KexibqRtvg#v3r!'
smtp_from: org.drupalcamp.kyiv@gmail.com
smtp_fromname: 'DrupalCamp Kyiv'
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
langcode: uk
smtp_client_hostname: ''
smtp_client_helo: ''
